language: python
dist: trusty
sudo: required
python:
  - 3.6
  - 3.5
env:
  global:
    - NO_SLOW=true
  matrix:
    - PANDAS_VERSION=0.18 NUMPY_VERSION=1.11
    - PANDAS_VERSION=0.19 NUMPY_VERSION=1.12
    - PANDAS_VERSION=0.20 NUMPY_VERSION=1.13 NO_SLOW=false

matrix:
  exclude:
    - python: 3.6
      env: PANDAS_VERSION=0.18 NUMPY_VERSION=1.11

cache:
  directories:
    - $HOME/miniconda3 # miniconda cache

# Setup miniconda
before_install:
  - export PATH=$HOME/miniconda3/bin:$PATH
  - ci/before_install_travis.sh

# command to install dependencies
install:
  - conda install -n sksurv-test -c sebp --file requirements.txt
  - source activate sksurv-test
  - python setup.py install
  - rm -fr sksurv

# command to run tests
script: |
  if [[ "x$NO_SLOW" != "xtrue" ]]; then
  nosetests -w tests --with-coverage --cover-xml --cover-package=sksurv --cover-tests
  else
  nosetests -w tests -a "!slow" --with-coverage --cover-xml --cover-package=sksurv --cover-tests
  fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - pip install codacy-coverage
  - python-codacy-coverage -r coverage.xml
